import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "63",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[접합]대로3류,[접합]중로1류,[접합]소로1류",
      DEAL_MM: "05",
      BLDG_NM: "롯데1단지",
      BUBN: null,
      HO_CODE: 27,
      ROAD_LEN: "25m이상",
      BLDG_CD: 16729,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "116~120%",
      BLDG_AREA: 141.72,
      APTFNO: 5,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]기타<도시및주거환경정비법>(용호1 주택재건축정비예정구역)",
      SUM_AMT: "118,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "21~25%",
      DNAME: "용호동",
      BUILD_YEAR: 1984,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트",
    },
    {
      BOBN: "63",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[접합]대로3류,[접합]중로1류,[접합]소로1류",
      DEAL_MM: "03",
      BLDG_NM: "롯데1단지",
      BUBN: null,
      HO_CODE: 4,
      ROAD_LEN: "25m이상",
      BLDG_CD: 16729,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "116~120%",
      BLDG_AREA: 79.95,
      APTFNO: 1,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]기타<도시및주거환경정비법>(용호1 주택재건축정비예정구역)",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "21~25%",
      DNAME: "용호동",
      BUILD_YEAR: 1984,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트조",
    },
    {
      BOBN: "63",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[접합]대로3류,[접합]중로1류,[접합]소로1류",
      DEAL_MM: "01",
      BLDG_NM: "롯데1단지",
      BUBN: null,
      HO_CODE: 24,
      ROAD_LEN: "25m이상",
      BLDG_CD: 16729,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "116~120%",
      BLDG_AREA: 82.53,
      APTFNO: 3,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]기타<도시및주거환경정비법>(용호1 주택재건축정비예정구역)",
      SUM_AMT: "58,500",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "21~25%",
      DNAME: "용호동",
      BUILD_YEAR: 1984,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트",
    },
  ]
  res.status(200).json(data)
}
