export const d22_1 = [
  {
    BOBN: "70",
    BLDG_ROW: 1,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000625",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "110,300",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 1,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.7312,
    AREA_ROW: 1,
    BUILD_CNT: 1,
    AREA_CNT: 1,
  },
]

export const d22_2 = [
  {
    BOBN: "70",
    BLDG_ROW: 1,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002402",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7227,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "102,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.7227,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 2,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001940",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 2,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "102,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002523",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 30,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "105,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.7312,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d22_3 = [
  {
    BOBN: "70",
    BLDG_ROW: 1,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0007332",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7227,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "92,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.7227,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 2,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005596",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "100,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "09",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008432",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 10,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "92,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.7312,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 3,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006325",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 114.807,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "148,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 114.807,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_4 = []

export const d23_1 = [
  {
    BOBN: "70",
    BLDG_ROW: 1,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002972",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.4592,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.4592,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 2,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001093",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7227,
        DPOS_GBN: "2",
        DEAL_DD: 18,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "73,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003359",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7227,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "79,800",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002287",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7227,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 1,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "72,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.7227,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 3,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 1,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002154",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "70,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003149",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "88,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003190",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 12,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "80,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.7312,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "70",
    BLDG_ROW: 4,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003845",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 100.1915,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 10,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "105,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 4,
    month2List: [],
    BLDG_AREA: 100.1915,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
]

export const d23_2 = [
  {
    BOBN: "70",
    BLDG_ROW: 1,
    BLDG_NM: "용지아이파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004027",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "83,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "70",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지아이파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004221",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20356516,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.7312,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "84,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20356516,
    BUILD_YEAR: 2017,
    BLDG_CNT: 1,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.7312,
    AREA_ROW: 1,
    BUILD_CNT: 1,
    AREA_CNT: 1,
  },
]
