import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "12",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 58,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.8848,
      APTFNO: 16,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "11",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 98,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 26,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "80,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "11",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 134,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 115.7299,
      APTFNO: 35,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "102,000",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구, 경남 함안군",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "11",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 1,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 2,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "11",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 125,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 33,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "70,500",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "10",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 50,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 14,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "80,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "10",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 19,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 115.7299,
      APTFNO: 6,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "115,400",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "09",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 119,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 31,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "57,400",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "09",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 92,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 24,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "57,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "08",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 84,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 18,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "83,150",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "08",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 35,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 10,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "57,700",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "08",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 99,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 21,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "83,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "08",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 6,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 3,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "95,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "07",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 24,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 7,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "76,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "05",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 55,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 15,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "89,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 107,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.8848,
      APTFNO: 28,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "81,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 70,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 19,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "90,000",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 99,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 26,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "95,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 83,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 115.7299,
      APTFNO: 18,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "144,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 29,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 9,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "66,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 131,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 34,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "94,900",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 22,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 7,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "89,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 17,
      DEAL_DD: 4,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "68,900",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: "20220329",
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 17,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "68,900",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 17,
      DEAL_DD: 4,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "69,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: "20220315",
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 31,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 9,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "67,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
