import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "05",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 24,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 7,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "79,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 2,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 110,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 29,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "96,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 41,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 12,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "78,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 117,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.8848,
      APTFNO: 31,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "59,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "04",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 12,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 4,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "90,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 166,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 34,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "81,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 76,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 20,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "76,000",
      RDEALER_LAWDNM: "경남 창원마산합포구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 148,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 32,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "79,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 135,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 28,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "80,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "03",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 57,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.8848,
      APTFNO: 16,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 124,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 32,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "55,000",
      RDEALER_LAWDNM: "경남 거제시",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 13,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 5,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "55,250",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 82,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 22,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "78,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 124,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 32,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "89,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 68,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.9816,
      APTFNO: 18,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "56,300",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "02",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 4,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 2,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "66,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 8,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "93,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 102,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 27,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "71,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 123,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.1031,
      APTFNO: 32,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "74,800",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 111,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 115.7299,
      APTFNO: 29,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "130,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 57,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.3838,
      APTFNO: 16,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "69,000",
      RDEALER_LAWDNM: "경남 창원마산합포구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "790",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]제2종일반주거지역,[접합]자연녹지지역,[접합]중로1류,[접합]중로2류,[접합]근린공원,[접합]경관녹지,[접합]중학교",
      DEAL_MM: "01",
      BLDG_NM: "창원중동유니시티1단지",
      BUBN: null,
      HO_CODE: 69,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20391947,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 99.1742,
      APTFNO: 19,
      DEAL_DD: 9,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]국가산업단지<산업입지및개발에관한법률>,[저촉]상대정화구역<학교보건법>(의창초등학교),[저촉]상대정화구역<학교보건법>(중학교 설립예정지),[저촉]절대정화구역<학교보건법>(중학교 설립예정지)",
      SUM_AMT: "86,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "중동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원의창구  중동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
