import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "12",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 86,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 24,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "10",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 8,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 108.2567,
      APTFNO: 3,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "73,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "09",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 21,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.2572,
      APTFNO: 7,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "48,500",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "08",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 28,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 7,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "52,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "08",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 127,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 35,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "69,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "06",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 68,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 15,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "54,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "06",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 93,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 20,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "59,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "06",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 98,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 21,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,300",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "06",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 29,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 9,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "75,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 109,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.2572,
      APTFNO: 23,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 107,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 29,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "72,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 76,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.4068,
      APTFNO: 21,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "74,700",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 54,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 16,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "76,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 14,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.22,
      APTFNO: 9,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "71,000",
      RDEALER_LAWDNM: "경남 창원마산합포구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 80,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.4068,
      APTFNO: 22,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "72,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 30,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 7,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "59,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 17,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "73,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 96,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.2572,
      APTFNO: 21,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 60,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 13,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "61,000",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
