import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 65,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 18,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경남 창원마산합포구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 31,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.1992,
      APTFNO: 8,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "54,800",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 18,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 6,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "45,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 47,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 13,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "05",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 79,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 21,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "63,000",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 93,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 25,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 70,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.2843,
      APTFNO: 19,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "63,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 49,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.1992,
      APTFNO: 11,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "54,900",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 73,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 16,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "47,300",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 9,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "47,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 98,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 21,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "47,700",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "04",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 8,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.2843,
      APTFNO: 3,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 120,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 25,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "47,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 94,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.22,
      APTFNO: 25,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 47,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 11,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "44,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 86,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 23,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "45,700",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 54,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.2843,
      APTFNO: 15,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 16,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 5,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "44,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.1992,
      APTFNO: 7,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "55,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 8,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "03",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 59,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 17,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 110,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 30,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "60,200",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 14,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 11,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "63,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 29,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.1992,
      APTFNO: 9,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "53,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 87,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 23,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 15,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "44,300",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 75,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 16,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "44,800",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 54,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.2843,
      APTFNO: 15,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "59,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 9,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "43,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "02",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 11,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 4,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "53,500",
      RDEALER_LAWDNM: "경남 김해시",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 98,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 68.22,
      APTFNO: 21,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "53,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 83,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 23,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 97,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.353,
      APTFNO: 26,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 122,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 26,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "43,500",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 113,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 24,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "44,500",
      RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 59.0578,
      APTFNO: 11,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "43,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "40",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]어린이공원",
      DEAL_MM: "01",
      BLDG_NM: "포레나대원",
      BUBN: null,
      HO_CODE: 42,
      ROAD_LEN: "25m미만",
      BLDG_CD: 20385010,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "216~220%",
      BLDG_AREA: 84.2843,
      APTFNO: 12,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(대원2구역 주택재건축사업),[저촉]상대정화구역<학교보건법>(대원3구역_유치원예정지),[저촉]상대정화구역<학교보건법>(대원초등학교),[저촉]상대정화구역<학교보건법>(창원공업고등학교),[접합]국가산업단지<산업입지및개발에관한법률>",
      SUM_AMT: "57,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "대원동",
      BUILD_YEAR: 2018,
      JIBUN_NAME: "경상남도 창원성산구  대원동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
