export const d22_1 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000533",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "61,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001433",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.0578,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000938",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.2572,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 59.2572,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 3,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원마산합포구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001507",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.22,
        DPOS_GBN: "2",
        DEAL_DD: 6,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "71,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 68.22,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 4,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원의창구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001730",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "76,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001389",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "73,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 5,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 2,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001923",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.4068,
        DPOS_GBN: "2",
        DEAL_DD: 5,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "72,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001959",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.4068,
        DPOS_GBN: "2",
        DEAL_DD: 19,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "74,700",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 5,
    month2List: [],
    BLDG_AREA: 84.4068,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
]

export const d22_2 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 3,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003336",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,300",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005299",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005599",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 59.0578,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002941",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.2572,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.2572,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 3,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002681",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 29,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "72,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003130",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "75,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_3 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0007342",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 19,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.0578,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원의창구",
        DEAL_MM: "09",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008704",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.2572,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "48,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 59.2572,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 3,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원의창구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006642",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 35,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_4 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009185",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008985",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 108.2567,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "73,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 108.2567,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d23_1 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 4,
    CNT2: 3,
    CNT1: 3,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원의창구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000421",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 5,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "43,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002464",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 26,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002294",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "43,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003212",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 5,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003373",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,700",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003485",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003658",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 25,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "47,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002288",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "43,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002613",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,800",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002603",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,300",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.0578,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: null,
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003766",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.1992,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "직거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003193",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.1992,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "53,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 68.1992,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 3,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002448",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.22,
        DPOS_GBN: "2",
        DEAL_DD: 31,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "53,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003622",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.22,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 25,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 68.22,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 4,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000210",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.2843,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 12,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003307",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.2843,
        DPOS_GBN: "2",
        DEAL_DD: 6,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002396",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.2843,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.2843,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 5,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 1,
    CNT2: 4,
    CNT1: 2,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002379",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 30,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002484",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 31,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003537",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 2,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 5,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 김해시",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002461",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 2,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "53,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002532",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003482",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003269",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 23,
        APTFNO: 30,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,200",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
]

export const d23_2 = [
  {
    BOBN: "40",
    BLDG_ROW: 1,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 3,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004087",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 8,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "47,700",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003960",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "47,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004057",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "47,300",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004558",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.0578,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 6,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.0578,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 2,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004316",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.1992,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,900",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004451",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 68.1992,
        DPOS_GBN: "2",
        DEAL_DD: 6,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,800",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 68.1992,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 3,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004191",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.2843,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004426",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.2843,
        DPOS_GBN: "2",
        DEAL_DD: 27,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.2843,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "40",
    BLDG_ROW: 4,
    BLDG_NM: "포레나대원",
    BUBN: null,
    CNT3: 0,
    CNT2: 3,
    CNT1: 1,
    month1List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004457",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 25,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20385010,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원의창구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004396",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004684",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "40",
        RDEALER_LAWDNM: "경남 창원마산합포구, 경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "포레나대원",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004491",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20385010,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.353,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.353,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
]
