import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 74,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6825,
      APTFNO: 16,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "26,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 6,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 21,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6825,
      APTFNO: 5,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "36,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 125,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 17,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 195,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 26,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "22,500",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 56,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 15,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "48,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "12",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 191,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 25,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "11",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 50,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.1787,
      APTFNO: 11,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "40,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "11",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 9,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 3,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "43,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "11",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 27,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6947,
      APTFNO: 6,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "36,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "10",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 106,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6825,
      APTFNO: 22,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "39,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "09",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 102,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 14,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "09",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 112,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 29,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "58,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "08",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 10,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "55,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "08",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 112,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 29,
      DEAL_DD: 14,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "58,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: "20220913",
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "07",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 194,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 25,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "07",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 173,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 23,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,300",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "06",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 34,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6825,
      APTFNO: 8,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "43,800",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "06",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 137,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6825,
      APTFNO: 28,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "44,800",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 75,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.1787,
      APTFNO: 16,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "52,500",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 66,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 9,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "23,900",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 158,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 21,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 162,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 21,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 113,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 15,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,400",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 96,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 13,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "21,400",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 153,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 20,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "05",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 169,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 22,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "20,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 34,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 72.1787,
      APTFNO: 8,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "49,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 2,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 1,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "23,800",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 16,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 3,
      DEAL_DD: 25,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "21,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: "20221201",
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 190,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 25,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,300",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 95,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 13,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,400",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 199,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 26,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 75,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 19,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "34,600",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 12,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "04",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 97,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6947,
      APTFNO: 20,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "46,900",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 84,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 51.5654,
      APTFNO: 18,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "37,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 145,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 19,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 102,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 14,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 111,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 15,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,400",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 176,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 23,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "22,000",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 24,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9952,
      APTFNO: 6,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 89,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 12,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,400",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 126,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 59.6947,
      APTFNO: 26,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "44,400",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 182,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 24,
      DEAL_DD: 12,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,300",
      RDEALER_LAWDNM: "경남 창원마산합포구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 24,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 51.5654,
      APTFNO: 6,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "33,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 144,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 19,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "21,900",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 128,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 17,
      DEAL_DD: 9,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "03",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 198,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 26,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,500",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "02",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 106,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 14,
      DEAL_DD: 28,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,400",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: "20230226",
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "02",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 120,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 16,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "02",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 93,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 13,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "02",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 102,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 71.2807,
      APTFNO: 21,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "48,800",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 121,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 16,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "24,700",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 144,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 19,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "21,700",
      RDEALER_LAWDNM: "경남 창원의창구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 181,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 38.828,
      APTFNO: 24,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "25,300",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 117,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9409,
      APTFNO: 30,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 9,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9952,
      APTFNO: 4,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "58,500",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "300",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[포함]지구단위계획구역,[저촉]대로1류,[저촉]중로1류,[저촉]중로2류,[접합]제2종일반주거지역",
      DEAL_MM: "01",
      BLDG_NM: "창원메트로시티석전",
      BUBN: null,
      HO_CODE: 92,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20401811,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "246~250%",
      BLDG_AREA: 84.9952,
      APTFNO: 24,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[포함]정비구역<도시및주거환경정비법>(석전1구역 주택재개발사업),[저촉]상대정화구역<학교보건법>(북성초등학교)",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경남 창원마산회원구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "석전동",
      BUILD_YEAR: 2019,
      JIBUN_NAME: "경상남도 창원마산회원구  석전동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
