export const d22_1 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000405",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "67,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001755",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "75,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.9968,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d22_2 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 2,
    CNT2: 2,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002124",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005192",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005263",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002826",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,100",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002923",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,100",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9573,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002883",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003138",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 3,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 2,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003570",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 27,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "76,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003572",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "70,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002790",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 11,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "75,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9004,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 4,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005431",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 27,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "75,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002913",
        CNTL_YMD: "20220727",
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "C",
        DEAL_DD: 21,
        APTFNO: 5,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "74,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9968,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
]

export const d22_3 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: null,
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0007694",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 17,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "직거래",
        SUM_AMT: "65,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006842",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9584,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "67,800",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9584,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 3,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구, 경남 창원의창구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006661",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 6,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,900",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006578",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 27,
        APTFNO: 5,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "74,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "09",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008461",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "67,900",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.9968,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_4 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 3,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009355",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "42,900",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000116",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "46,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009512",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "42,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 59.9573,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 2,
    CNT2: 1,
    CNT1: 2,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: null,
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008588",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "직거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008671",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009340",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 17,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "49,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009532",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "50,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "11",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009186",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,800",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 3,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 3,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008565",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 29,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "71,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008808",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 5,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "64,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008827",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 25,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "11",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009131",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 18,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9004,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 4,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000180",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9584,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "11",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009105",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9584,
        DPOS_GBN: "2",
        DEAL_DD: 12,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9584,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 5,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008444",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 12,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "68,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [],
    BUILD_ROW: 5,
    month2List: [],
    BLDG_AREA: 84.9968,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 6,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 6,
    month3List: [],
    BUILD_ROW: 6,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "11",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008833",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 101.9376,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "70,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 101.9376,
    AREA_ROW: 1,
    BUILD_CNT: 6,
    AREA_CNT: 1,
  },
]

export const d23_1 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 5,
    CNT1: 6,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004011",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "42,600",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001096",
        CNTL_YMD: "20230417",
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "C",
        DEAL_DD: 7,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "42,600",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000478",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002179",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "44,700",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001109",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001090",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "46,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002162",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002644",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 17,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "49,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003133",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003118",
        CNTL_YMD: "20230302",
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "C",
        DEAL_DD: 25,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003117",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "46,700",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9573,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 김해시, 경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000859",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 3,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000911",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002531",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 29,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003095",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 6,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,200",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9004,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 4,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 4,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002261",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9584,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9584,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 5,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 5,
    month3List: [],
    BUILD_ROW: 5,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원마산합포구, 경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002213",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9968,
        DPOS_GBN: "2",
        DEAL_DD: 5,
        APTFNO: 10,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9968,
    AREA_ROW: 1,
    BUILD_CNT: 5,
    AREA_CNT: 1,
  },
]

export const d23_2 = [
  {
    BOBN: "12",
    BLDG_ROW: 1,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004200",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 27,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "50,900",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004380",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 59.9573,
        DPOS_GBN: "2",
        DEAL_DD: 9,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "48,750",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9573,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 2,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004277",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 2,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004315",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 73.7334,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,600",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 73.7334,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "12",
    BLDG_ROW: 3,
    BLDG_NM: "창원센텀푸르지오",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "12",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원센텀푸르지오",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004171",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360987,
        BUILD_YEAR: 2018,
        BLDG_AREA: 84.9004,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,300",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360987,
    BUILD_YEAR: 2018,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.9004,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]
