export const d22_1 = [
  {
    BOBN: "69",
    BLDG_ROW: 1,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000157",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "100,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000902",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "103,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.475,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 2,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001880",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 101.9047,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "136,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 101.9047,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d22_2 = []

export const d22_3 = [
  {
    BOBN: "69",
    BLDG_ROW: 1,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 1,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005654",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 18,
        APTFNO: 2,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,100",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006944",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "67,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "08",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006943",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 22,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "70,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9975,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 2,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "09",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0007773",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 119.2427,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "156,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 119.2427,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d22_4 = [
  {
    BOBN: "69",
    BLDG_ROW: 1,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000613",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 30,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "76,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.475,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 2,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008902",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2022",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 101.9047,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "120,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 101.9047,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d23_1 = [
  {
    BOBN: "69",
    BLDG_ROW: 1,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 1,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000615",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 12,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,800",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002212",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002521",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 6,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9975,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 2,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 2,
    CNT2: 4,
    CNT1: 3,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002257",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "73,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002155",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "82,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002445",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 31,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "83,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 2,
    month3List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003447",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "85,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003470",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 8,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "80,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002419",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 2,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "86,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002482",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "87,800",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002625",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "84,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002629",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "84,500",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.475,
    AREA_ROW: 1,
    BUILD_CNT: 2,
    AREA_CNT: 1,
  },
]

export const d23_2 = [
  {
    BOBN: "69",
    BLDG_ROW: 1,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004240",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 28,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004461",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9975,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9975,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 2,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003891",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "90,400",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004234",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.475,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "87,800",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.475,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 3,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004405",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 101.9047,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "119,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 101.9047,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "69",
    BLDG_ROW: 4,
    BLDG_NM: "용지더샵레이크파크",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "69",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "용지더샵레이크파크",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003970",
        CNTL_YMD: null,
        ROAD_LEN: "25m미만",
        ACC_YEAR: "2023",
        BLDG_CD: 20360277,
        BUILD_YEAR: 2017,
        BLDG_AREA: 119.2427,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 2,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "140,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m미만",
    BLDG_CD: 20360277,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 4,
    month2List: [],
    BLDG_AREA: 119.2427,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
]
