import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 108,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 23,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "52,200",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 54,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 12,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "52,500",
      RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 122,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 26,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "55,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "11",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 70.9062,
      APTFNO: 15,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "52,100",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "10",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 6,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 100.614,
      APTFNO: 3,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "07",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 74,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 16,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "67,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "06",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 94,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 20,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "66,600",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "06",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 53,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 15,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "54,900",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 33,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 8,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "69,900",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 9,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 65,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 14,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "74,500",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 105,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 22,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "72,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 123,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 26,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "63,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 59,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 13,
      DEAL_DD: 12,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "72,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: "20221115",
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 100.614,
      APTFNO: 15,
      DEAL_DD: 12,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "80,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 32,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 9,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "70,250",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
