import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 74,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 16,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "56,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 23,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 7,
      DEAL_DD: 19,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "45,800",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 82,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 70.9062,
      APTFNO: 18,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "53,700",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 79,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 21,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "46,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 124,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 26,
      DEAL_DD: 12,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "55,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 121,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 70.9062,
      APTFNO: 26,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "48,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 69,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 19,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "46,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 44,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 10,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 15,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 4,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "54,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 21,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 7,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "59,300",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 115,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 24,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 9,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 4,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "45,200",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 83,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 18,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 72,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 16,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 9,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "60,900",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 93,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 20,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "61,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 105,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 22,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 19,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 5,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 124,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 26,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "57,900",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 91,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 20,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "58,700",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 44,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 10,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 52,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 12,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "54,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 11,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "52,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 79,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 17,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "53,400",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 120,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 25,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.9921,
      APTFNO: 11,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "42,800",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 103,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 22,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "55,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 123,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9763,
      APTFNO: 26,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "13",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "창원가음한화꿈에그린",
      BUBN: null,
      HO_CODE: 59,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20358987,
      LAND_MOVE1: "201*",
      LAND_MOVE2: "토지개발사업 완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 84.9521,
      APTFNO: 13,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(남정초등학교),[저촉]상대정화구역<학교보건법>(창원천광학교)",
      SUM_AMT: "52,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "가음동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  가음동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
