export const d22_1 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001537",
        CNTL_YMD: "20221115",
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "C",
        DEAL_DD: 12,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "72,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 2,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001515",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 19,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "63,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001108",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 26,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "70,250",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9763,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 3,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001754",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 100.614,
        DPOS_GBN: "2",
        DEAL_DD: 12,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "80,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 100.614,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_2 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003142",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,900",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 59.9921,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 2,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "06",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0005284",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "66,600",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 3,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 2,
    CNT1: 2,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002122",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "72,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: null,
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002659",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 14,
        SGG_CD: "48123",
        REQ_GBN: "직거래",
        SUM_AMT: "74,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002793",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 13,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "68,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003194",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 8,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "69,900",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9763,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d22_3 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "07",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0006526",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 23,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "67,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 1,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 1,
    AREA_CNT: 1,
  },
]

export const d22_4 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "11",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009113",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 70.9062,
        DPOS_GBN: "2",
        DEAL_DD: 16,
        APTFNO: 15,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,100",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 70.9062,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 2,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 1,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원마산회원구, 경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009436",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 12,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,500",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 3,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 2,
    CNT2: 0,
    CNT1: 0,
    month1List: [],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0009437",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 4,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "12",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000581",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 31,
        APTFNO: 23,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,200",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.9763,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 4,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 1,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "10",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0008812",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2022",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 100.614,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 3,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 4,
    month3List: [],
    BUILD_ROW: 4,
    month2List: [],
    BLDG_AREA: 100.614,
    AREA_ROW: 1,
    BUILD_CNT: 4,
    AREA_CNT: 1,
  },
]

export const d23_1 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 1,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000378",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "42,800",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003120",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 25,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,200",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9921,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 2,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 4,
    CNT1: 2,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000244",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 13,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001111",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 18,
        APTFNO: 17,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "53,400",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002523",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 6,
        APTFNO: 10,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002538",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 10,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "57,900",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002480",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 5,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003103",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 21,
        APTFNO: 9,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,900",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 3,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 3,
    CNT2: 5,
    CNT1: 5,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000257",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000382",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 7,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0000561",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 14,
        APTFNO: 25,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "56,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0001082",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 27,
        APTFNO: 11,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "52,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "01",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002188",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 30,
        APTFNO: 12,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003461",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 3,
        APTFNO: 24,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003870",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 30,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "59,300",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "03",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003829",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 31,
        APTFNO: 4,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "54,000",
        OBJ_SEQNO: 1,
      },
    ],
    BUILD_ROW: 3,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0002312",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 8,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,700",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003125",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 15,
        APTFNO: 22,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003130",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 18,
        APTFNO: 20,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "61,500",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003104",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 23,
        APTFNO: 16,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "60,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "02",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003134",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9763,
        DPOS_GBN: "2",
        DEAL_DD: 24,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "58,000",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 84.9763,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]

export const d23_2 = [
  {
    BOBN: "13",
    BLDG_ROW: 1,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 1,
    CNT1: 2,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003802",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 2,
        APTFNO: 19,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "46,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004128",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 20,
        APTFNO: 21,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "46,000",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 1,
    month2List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "05",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004625",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 59.9921,
        DPOS_GBN: "2",
        DEAL_DD: 19,
        APTFNO: 7,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "45,800",
        OBJ_SEQNO: 1,
      },
    ],
    BLDG_AREA: 59.9921,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 2,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: null,
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004143",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 70.9062,
        DPOS_GBN: "2",
        DEAL_DD: 5,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "직거래",
        SUM_AMT: "48,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0004225",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 70.9062,
        DPOS_GBN: "2",
        DEAL_DD: 29,
        APTFNO: 18,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "53,700",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 2,
    month2List: [],
    BLDG_AREA: 70.9062,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
  {
    BOBN: "13",
    BLDG_ROW: 3,
    BLDG_NM: "창원가음한화꿈에그린",
    BUBN: null,
    CNT3: 0,
    CNT2: 0,
    CNT1: 2,
    month1List: [
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003775",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 1,
        APTFNO: 10,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "62,000",
        OBJ_SEQNO: 1,
      },
      {
        BOBN: "13",
        RDEALER_LAWDNM: "경남 창원성산구",
        DEAL_MM: "04",
        JOB_GBN: "4",
        BLDG_NM: "창원가음한화꿈에그린",
        OBJ_FIN_SEQNO: 1,
        BUBN: null,
        ACC_NO: "0003978",
        CNTL_YMD: null,
        ROAD_LEN: "25m이상",
        ACC_YEAR: "2023",
        BLDG_CD: 20358987,
        BUILD_YEAR: 2017,
        BLDG_AREA: 84.9521,
        DPOS_GBN: "2",
        DEAL_DD: 12,
        APTFNO: 26,
        SGG_CD: "48123",
        REQ_GBN: "중개거래",
        SUM_AMT: "55,500",
        OBJ_SEQNO: 1,
      },
    ],
    ROAD_LEN: "25m이상",
    BLDG_CD: 20358987,
    BUILD_YEAR: 2017,
    BLDG_CNT: 3,
    month3List: [],
    BUILD_ROW: 3,
    month2List: [],
    BLDG_AREA: 84.9521,
    AREA_ROW: 1,
    BUILD_CNT: 3,
    AREA_CNT: 1,
  },
]
