import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "12",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 73,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 4,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "61,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "11",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 82,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 22,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "81,000",
      RDEALER_LAWDNM: "서울 관악구, 서울 동작구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 20,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "08",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 143,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 9,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "94,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 19,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "08",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 6,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 114.69,
      APTFNO: 11,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "120,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 18,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "07",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 87,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.2,
      APTFNO: 22,
      DEAL_DD: 7,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "72,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: "20220801",
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 7,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "06",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 11,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 11,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "107,500",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 13,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "05",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 103,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 6,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "91,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 21,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "05",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 17,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 11,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "89,500",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 115,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 9,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "90,100",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 83,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 9,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "85,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 13,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 30,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 14,
      DEAL_DD: 12,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "89,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 19,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "03",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.2,
      APTFNO: 13,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "107,700",
      RDEALER_LAWDNM: "서울 관악구, 서울 동작구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "03",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 65,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 19,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "87,500",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 87,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 7,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "90,500",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]공공도서관",
      DEAL_MM: "01",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 20,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 13,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]학교환경위생정화구역<학교보건법>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "93,250",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
