import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "05",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 87,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.2,
      APTFNO: 22,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 7,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "05",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 18,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "84,500",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "05",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 37,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 18,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "84,300",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 7,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 1,
      DEAL_DD: 26,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "61,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 20,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 85,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 3,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 21,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 68,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 24,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "73,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 23,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 12,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "66,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "04",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 54,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 18,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "70,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "03",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 65,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 19,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "03",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 36,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 17,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "87,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 100,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 6,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "65,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 21,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 41,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 19,
      DEAL_DD: 23,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "70,000",
      RDEALER_LAWDNM: "서울 관악구, 서울 동작구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 15,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 51,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.2,
      APTFNO: 17,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "95,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 19,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 15,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 84.75,
      APTFNO: 12,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "86,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1717",
      LAND_USE_NM:
        "[포함]제3종일반주거지역,[접합]제2종일반주거지역,[접합]제3종일반주거지역,[접합]도로,[접합]중로2류,[접합]공공도서관",
      DEAL_MM: "02",
      BLDG_NM: "관악푸르지오",
      BUBN: null,
      HO_CODE: 77,
      ROAD_LEN: "25m미만",
      BLDG_CD: 52440,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "구획정리완료",
      GRND_FLR_CNT: "-",
      VL_RAT: "291~295%",
      BLDG_AREA: 59.58,
      APTFNO: 6,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]대공방어협조구역<군사기지 및 군사시설보호법>(위탁고도:194m),[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]과밀억제권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>,[저촉]교육환경보호구역<교육환경보호에관한법률>(상대/절대정화구역 최종확인은 동작교육청에 반드시 확인이 필요한 사항임)",
      SUM_AMT: "67,000",
      RDEALER_LAWDNM: "서울 관악구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "봉천동",
      BUILD_YEAR: 2004,
      JIBUN_NAME: "서울특별시 관악구  봉천동",
      DONG_CODE: 16,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
