import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "09",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 10,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "92,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "08",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 74,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7227,
      APTFNO: 19,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "92,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "07",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 114.807,
      APTFNO: 17,
      DEAL_DD: 20,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "148,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "07",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 56,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 14,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "100,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "04",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 81,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 21,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "105,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "04",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 71,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7227,
      APTFNO: 18,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "102,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "04",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 49,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 13,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "102,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "01",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 87,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 22,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "110,300",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
