import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "04",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 35,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 9,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "84,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "04",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 56,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 14,
      DEAL_DD: 7,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "83,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "03",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 100.1915,
      APTFNO: 10,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "105,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "03",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 27,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7227,
      APTFNO: 7,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "79,800",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "02",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 45,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 12,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "80,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "02",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 73,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 19,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "88,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "02",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 80,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 59.4592,
      APTFNO: 20,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "02",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 3,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7227,
      APTFNO: 1,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "72,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "01",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 51,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7227,
      APTFNO: 13,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "73,500",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "70",
      LAND_USE_NM:
        "[포함]제2종전용주거지역,[포함]지구단위계획구역,[접합]대로3류,[접합]중로1류,[접합]중로2류,[접합]소공원,[접합]완충녹지,[접합]고등학교",
      DEAL_MM: "01",
      BLDG_NM: "용지아이파크",
      BUBN: null,
      HO_CODE: 16,
      ROAD_LEN: "25m이상",
      BLDG_CD: 20356516,
      LAND_MOVE1: "202*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "206~210%",
      BLDG_AREA: 84.7312,
      APTFNO: 4,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>(전부제한),[저촉]상대정화구역<학교보건법>,[저촉]상대정화구역<학교보건법>(용호초등학교),[저촉]상대정화구역<학교보건법>(창원중앙고등학교),[저촉]절대정화구역<학교보건법>(창원중앙고등학교),[접합]자연재해위험지구<자연재해대책법>",
      SUM_AMT: "70,000",
      RDEALER_LAWDNM: "경남 창원성산구",
      CNTL_YMD: null,
      BC_RAT: "11~15%",
      DNAME: "용호동",
      BUILD_YEAR: 2017,
      JIBUN_NAME: "경상남도 창원성산구  용호동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
