import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,100",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 64,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 7,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "70,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "12",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 13,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 12,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "09",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 5,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 1,
      DEAL_DD: 30,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "61,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "09",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 27,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 15,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "70,800",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "09",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 20,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "71,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "09",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 40,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 15,
      DEAL_DD: 3,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,800",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "08",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 85,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 6,
      DEAL_DD: 9,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "73,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "06",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 46,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 16,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "78,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]제1종지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 20,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 12,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "82,500",
      RDEALER_LAWDNM: "경기 용인수지구, 서울 종로구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 14,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 12,
      DEAL_DD: 24,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "82,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 16,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 12,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "83,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]제1종지구단위계획구역,[포함]토지거래계약에관한허가구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 27,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 31,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "85,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]제1종지구단위계획구역,[포함]토지거래계약에관한허가구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 12,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 11,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "84,200",
      RDEALER_LAWDNM: "경기 용인기흥구, 경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]제1종지구단위계획구역,[포함]토지거래계약에관한허가구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 59,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.34,
      APTFNO: 4,
      DEAL_DD: 5,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "79,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
