import type { NextApiRequest, NextApiResponse } from "next"

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<any>
) {
  const data = [
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "05",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 9,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 11,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "69,300",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 69,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 20,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 4,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 60,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 6,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "69,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 2,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 15,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 72,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 9,
      DEAL_DD: 22,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 남양주시, 경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 50,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 10,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: "20230502",
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 50,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 3,
      DEAL_DD: 6,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 62,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 5,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "04",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 1,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "69,400",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 42,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 29,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 46,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 3,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 42,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 21,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "48,000",
      RDEALER_LAWDNM: "-",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 2,
      REQ_GBN: "직거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 15,
      DEAL_DD: 20,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: "20230427",
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 7,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 4,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 10,
      DEAL_DD: 8,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "63,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 58,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 4,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 3,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "03",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 39,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.34,
      APTFNO: 18,
      DEAL_DD: 2,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,300",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 41,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 19,
      DEAL_DD: 28,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: "20230315",
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 41,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 19,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 63,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 25,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "61,900",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: "20230316",
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 63,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 2,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "61,900",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 12,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 38,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 18,
      DEAL_DD: 25,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 11,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 67,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.34,
      APTFNO: 6,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 22,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 14,
      DEAL_DD: 18,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,000",
      RDEALER_LAWDNM: "경기 성남분당구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 97,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 8,
      DEAL_DD: 17,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 15,
      DPOS_GBN: "C",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: "20230310",
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 26,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "68,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 106,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 9,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 15,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 12,
      DEAL_DD: 11,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 7,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 5,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 10,
      DEAL_DD: 10,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "02",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 70,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 9,
      DEAL_DD: 4,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "58,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 98,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 8,
      DEAL_DD: 28,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "62,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 10,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 93,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 7,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 30,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 13,
      DEAL_DD: 27,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "64,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 8,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 41,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 19,
      DEAL_DD: 16,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "60,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 9,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 61,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 7,
      DEAL_DD: 15,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "59,500",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 6,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 49,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 4,
      DEAL_DD: 14,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "56,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 1,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
    {
      BOBN: "1065",
      LAND_USE_NM:
        "[포함]도시지역,[포함]제3종일반주거지역,[포함]지구단위계획구역,[접합]대로2류,[접합]중로1류,[접합]소로2류,[접합]소로3류,[접합]완충녹지",
      DEAL_MM: "01",
      BLDG_NM: "신정마을주공1",
      BUBN: null,
      HO_CODE: 3,
      ROAD_LEN: "25m이상",
      BLDG_CD: 8341,
      LAND_MOVE1: "200*",
      LAND_MOVE2: "행정관할구역변경",
      GRND_FLR_CNT: "-",
      VL_RAT: "211~215%",
      BLDG_AREA: 59.39,
      APTFNO: 10,
      DEAL_DD: 13,
      DPOS_GBN: "2",
      LAND_USE_LAW:
        "[포함]비행안전제3구역(전술)<군사기지 및 군사시설보호법>,[포함]가축사육제한구역<가축분뇨의관리및이용에관한법률>,[포함]성장관리권역<수도권정비계획법>,[저촉]상대정화구역<학교보건법>,[저촉]절대정화구역<학교보건법>",
      SUM_AMT: "65,000",
      RDEALER_LAWDNM: "경기 용인수지구",
      CNTL_YMD: null,
      BC_RAT: "16~20%",
      DNAME: "풍덕천동",
      BUILD_YEAR: 2000,
      JIBUN_NAME: "경기도 용인수지구  풍덕천동",
      DONG_CODE: 5,
      REQ_GBN: "중개거래",
      ETC_STRCT: "철근콘크리트구조",
    },
  ]
  res.status(200).json(data)
}
